package com.team.teamup.domain.enums;

public enum UserStatus {
    INTERN, JUNIOR, MID, SENIOR, TECH_LEAD, ADMIN, MODULE_LEAD, TECHNICAL_LEAD, TECHNICAL_LEAD_MANAGER, TECHNICAL_MANAGER, ENGINEERING_MANAGER
}
